### PR TITLE
Add render_views to readme

### PR DESCRIPTION
**Pull request by st0012**

### CODE REVIEW

**Comment by st0012** [comment]
This is for #66

**Comment by zachmargolis** [comment]
How are you rendering your JSON? Are you using Jbuilder or something? A plain `render json:` has worked fine for me in multiple projets

**Comment by st0012** [comment]
I am using jbuilder, but I don't specify what to render in my action, I use before action to set format to be `:json`, and seems that in this case fdoc can't get the view in tests.

**Comment by st0012** [comment]
And if I use `FDOC_SCAFFOLD=true` to generate `.fdoc` file, the `responseParameters`'s value will be just a `{}`

**Pull request closed without merging**
